### ISSUE TITLE
[update-living-situation] add 3 view fields on top of form for user's reference

### ISSUE THREAD

**Issue by jroedel** [Girolabs/fathersApp#128]
**Comportamiento actual**

El usuario no tiene certeza de cuál situación de vivienda está modificando

**Comportamiento deseado**

Agregar 3 datos encima del formulario de modificar una situación de vivienda:
1. El nombre de la persona
2. La filial de la situación de vivienda
3. La casa de la situación de vivienda

![WhatsApp Image 2020-10-05 at 7 56 36 PM](https://user-images.githubusercontent.com/3315281/95125734-ef5dbb00-0744-11eb-8c2d-0a6f84c0e9f9.jpeg)

**Comment by Guillecaba** [comment]
en dev
