### ISSUE TITLE
[bulletin-board] unread count indicator in lateral menu not updated

### ISSUE THREAD

**Issue by jroedel** [Girolabs/fathersApp#129]
**Comportamiento actual**

Cuando se entra a la pantalla "Recursos y noticias", no se actualiza el indicador de nuevos posts en el menú lateral.

Por claridad: actualizar el indicador consiste en llamar el endpoint `/:lang/api/v1/bulletin-board/check-for-unseen-posts` y poner el resultado en el menú lateral.

Para fines de debugging: se puede llamar `/es/api/v1/bulletin-board/3/mark-post?action=unseen` para marcar un post no-leído.

**Comportamiento deseado**

Se debe actualizar el indicador de nuevos posts en el menú lateral en los siguientes 2 casos:

- Se carga la pantalla principal (calendario)
- Se abre la sección "Recursos y noticias"

**Comment by Guillecaba** [comment]
in dev
