### ISSUE TITLE
[course-detail] missing dead people and ex-members in CourseDetail

### ISSUE THREAD

**Issue by jroedel** [Girolabs/fathersApp#130]
**Comportamiento actual**

No se muestran personas fallecidas ni ex-miembros en el detalle de curso. 

Ejemplo: [Pater ad Familiam Pentecostes uniens](https://schoenstatt-fathers.link/en/courses/31) (curso 31)

**Comportamiento deseado**

Porfa agrégalos en CourseDetail. Para fallecidas se puede agregar ` (✝1993)` y para ex-miembros `(×2018)`.

**Comment by Guillecaba** [comment]
en dev
