### ISSUE TITLE
[father-form] fix "cell phone" field

### ISSUE THREAD

**Issue by jroedel** [Girolabs/fathersApp#131]
**Comportamiento actual**

Busca una persona con un número celular, edita sus datos. No aparece su número celular

**Comportamiento deseado**

Debe aparecer el número celular actual.

![WhatsApp Image 2020-10-05 at 8 40 13 PM](https://user-images.githubusercontent.com/3315281/95129769-02738980-074b-11eb-96ab-34da5e9cd60e.jpeg)

**Comment by Guillecaba** [comment]
Le estoy enviando el cellphone el playload, pero en la respuesta del server no figura ese campo en la lista de campos actualizados
![payload](https://user-images.githubusercontent.com/9329111/95222139-90448880-07ce-11eb-9056-5a21daa10032.png)
![response](https://user-images.githubusercontent.com/9329111/95222150-93d80f80-07ce-11eb-9908-1dec12f1ff94.png)

**Comment by jroedel** [comment]
Parece que estás mandando `cellphone` con p minúscula en vez de `cellPhone` con P mayúscula.

También, cellPhone tiene que comenzar con '+', pero la API te va a advertir:
```
{
    "status": "NOK",
    "result": {
        "invalidFields": [
            {
                "field": "cellPhone",
                "errorKey": "regexNotMatch",
                "message": "Please begin with '+' and the country code, and use only numbers, dash, space or parenthesis. ' ext. ##' may be added for extensions."
            }
        ]
    }
``` 
El regex está en el endpoint `interface-data`
