### ISSUE TITLE
[patre-detail] show "name day" without year

### ISSUE THREAD

**Issue by jroedel** [Girolabs/fathersApp#134]
**Comportamiento actual**

En el campo "Onomástico", se incluye el año 1900. Eso es artificial para guardarlo como fecha, pero debe aparecer sin año.

**Comportamiento deseado**

Aparezca sin año.

EN: July 25
ES: 25 de julio
PT: 25 de julio
DE: 25. Juli

![WhatsApp Image 2020-10-05 at 8 48 01 PM](https://user-images.githubusercontent.com/3315281/95130625-65195500-074c-11eb-9f0c-756d2629e796.jpeg)

**Comment by Guillecaba** [comment]
en dev
