### ISSUE TITLE
[patre-detail] Add plus sign for adding a new living situation

### ISSUE THREAD

**Issue by jroedel** [Girolabs/fathersApp#135]
Al lado del texto "Situaciones de vivienda", agrega un ["plus"](https://icons.expo.fyi/FontAwesome/plus), justificado a la derecha, lo que debe abrir el formulario para una nueva situación de vivienda.

Eso es en adición a los lapices al lado de "Fecha de inicio" y "Fecha de término" #89 

![WhatsApp Image 2020-10-05 at 8 56 28 PM](https://user-images.githubusercontent.com/3315281/95131275-4d8e9c00-074d-11eb-8613-5105b18bbfac.jpeg)

**Comment by Guillecaba** [comment]
dev
