### ISSUE TITLE
[father-form] On save, navigate to father's profile and display snack message

### ISSUE THREAD

**Issue by jroedel** [Girolabs/fathersApp#151]
## Reproducción de comportamiento

1. Editar una persona
2. Modificar algún campo
3. Presiona "Guardar"

## Comportamiento actual

Se vuelve a cargar el formulario de esa persona

## Comportamiento deseado

1. Se navega al perfil de esa persona
2. Se muestra un snack message "Persona actualizada exitosamente", "Person was successfully updated", "Person erfolgreich aktualisiert", "Pessoa atualizada com êxito!"

**Comment by Guillecaba** [comment]
en dev
