### ISSUE TITLE
App icon: something's not right

### ISSUE THREAD

**Issue by jroedel** [Girolabs/fathersApp#33]
Aquí pongo dos impresiones de pantalla que muestra que algo está malo con nuestro ícono en comparación a las demás apps. Debe ser algo de transparencia o algo. No sé, me imagino que el diseñadora de Uds deba saber.

![WhatsApp Image 2020-08-15 at 5 16 18 PM](https://user-images.githubusercontent.com/3315281/90317768-2076f780-df1b-11ea-9111-c98e3f7358b8.jpeg)

Aquí, las esquinas deben aparecer redondeadas:

![WhatsApp Image 2020-08-15 at 5 16 07 PM](https://user-images.githubusercontent.com/3315281/90317771-24a31500-df1b-11ea-9c99-aba3630ac8d5.jpeg)

**Comment by jroedel** [comment]
Volvió el problema del laucher hace unas semanas y nunca se vio bien en el selector de apps abiertas. 
![Screenshot_20200907-142203](https://user-images.githubusercontent.com/3315281/92413503-0d200c00-f116-11ea-92c5-586844d7a455.png)
![Screenshot_20200907-142155](https://user-images.githubusercontent.com/3315281/92413506-10b39300-f116-11ea-99b0-f43ff01ec3bb.png)

**Comment by jroedel** [comment]
https://developer.android.com/studio/write/image-asset-studio

**Comment by Guillecaba** [comment]
in dev
