### ISSUE TITLE
[bulletin-board] Text size buttons in top-right corner

### ISSUE THREAD

**Issue by jroedel** [Girolabs/fathersApp#44]
Podría ser útil para los mayores poder agrandar/achicar el tamaño del texto en la oración de comunidad y las noticias. 

Propongo dos botones en la esquina superior derecha de cada entrada del área "Recursos & noticias": uno para achicar el texto, otro para agrandarlo.

Sería bueno que la app recordara el tamaño de letra seleccionado

![WhatsApp Image 2020-08-20 at 3 40 17 PM](https://user-images.githubusercontent.com/3315281/90794211-0c0c7380-e2fc-11ea-9b26-20a84ff6d782.jpeg)

**Comment by Guillecaba** [comment]
The default size was changed to 1.5em
