### ISSUE TITLE
[father-form] Add more inputs

### ISSUE THREAD

**Issue by jroedel** [Girolabs/fathersApp#99]
Queremos los siguientes inputs agregados:

- lastName, string max 50 chars
- firstName, string max 50 chars
- friendlyFirstName: string max 50 chars
- friendlyLastName: string max 50 chars
- email: string, email maximo 70 chars
- email2: string, email maximo 70 chars
- [sé que ya pusiste 2 campos para teléfonos, pero los llenas desde la propiedad `phones`, tiene que ser de estos campos que ahora se entregan por la llamada GET]
- cellPhone (:lang/api/v1/interface-data["phoneNumberRegex"])
- cellPhoneHasWhatsApp, booleano [true, false]
- phone1, string regex (:lang/api/v1/interface-data["phoneNumberRegex"])
- phone1Label, select (:lang/api/v1/interface-data["personPhoneLabels"])
- phone2, string regex (:lang/api/v1/interface-data["phoneNumberRegex"])
- phone2Label, select (:lang/api/v1/interface-data["personPhoneLabels"])
- phone3, string regex (:lang/api/v1/interface-data["phoneNumberRegex"])
- phone3Label, select (:lang/api/v1/interface-data["personPhoneLabels"])
- [aqui en el orden, pueden ir los campos de información de contacto que ya existen]
- contactNotes, string maximo 2000 chars
- deaconDate, date YYYY-MM-DD
- priestDate, date YYYY-MM-DD
- bishopDate, date YYYY-MM-DD
- deathDate, date YYYY-MM-DD
- leaveDate, date YYYY-MM-DD
- emergencyContact1Name, string maximo 255 chars
- emergencyContact1Relation, select (:lang/api/v1/interface-data["personEmergencyContactRelationOptions"])
- emergencyContact1Phone, string regex (:lang/api/v1/interface-data["phoneNumberRegex"])
- emergencyContact2Name, string maximo 255 chars
- emergencyContact2Relation, select (:lang/api/v1/interface-data["personEmergencyContactRelationOptions"])
- emergencyContact2Phone, string regex (:lang/api/v1/interface-data["phoneNumberRegex"])

Por supuesto, no todos pueden editar todos los campos. Se puede saber cuáles el actual usuario puede editar por el siguiente proceso:
1. Se hace la llamada GET, por ejemplo `/es/api/v1/persons/667`. Las últimas propiedades son: 
```json
"viewPermissionForCurrentUser": "view-super-authorized",
"updatePermissionForCurrentUser": "update-super-authorized",
"allowCreateLivingSituation": true,
"allowUpdateLivingSituation": true,
"allowDeleteLivingSituation": true
```
Para edición, necesitamos ver `"updatePermissionForCurrentUser"`. Las posibilidades son: `"update"`, `"update-me"`, `"update-authorized"`, `"update-super-authorized"`.
2. Teniendo en cuenta los permisos que tiene el usuario hacia esta persona en particular, se hace referencia a :lang/api/v1/interface-data["personFieldsByUpdatePermission"] para ver específicamente cuáles campos corresponden a nuestro permiso de actualización

**Comment by Guillecaba** [comment]
en dev para android, pendiente en ios
